---
- name: Install Requirements
  yum: name={{ item }} state=latest
  with_items:
    - git
    - wget

- name: Add user git
  user: name=git comment=Gogs system=yes

- name: Create directory go
  sudo_user: git
  file: path=/home/git/go state=directory

- name: Export environment variables
  sudo_user: git
  lineinfile: dest=/home/git/.bashrc line="{{ item }}"
  with_items:
    - export GOPATH=$HOME/go
    - export PATH=$PATH:$GOPATH/bin

- name: Check gogs web
  shell: ps axu | grep  "^git .*/home/git/gogs/gogs web"
  register: gogs_exists
  ignore_errors: yes
  
- name: Install Gogs
  sudo_user: git
  environment:
    GOROOT: /usr/local/go
    GOPATH: /home/git/go
  shell: /usr/local/bin/go get -u github.com/gogits/gogs
  when: gogs_exists.rc != 0

- name: Build Gogs
  sudo_user: git
  environment:
    GOPATH: /home/git/go
  shell: cd /home/git/go/src/github.com/gogits/gogs &&
         /usr/local/bin/go build
  when: gogs_exists.rc != 0

- name: Create symling gogs
  sudo_user: git
  file: path=/home/git/gogs src=/home/git/go/src/github.com/gogits/gogs state=link

- name: Copy systemd settings
  shell: cp /home/git/go/src/github.com/gogits/gogs/scripts/systemd/gogs.service /lib/systemd/system/.
  
- name: Start gogs
  service: name=gogs state=restarted enabled=yes

- name: Create gogs db
  shell: echo CREATE DATABASE gogs | psql -U postgres
