---
- name: Create Drone.id Directory
  file: path=/var/lib/drone state=directory

- name: Create Database drone
  shell: echo 'CREATE DATABASE drone;' | psql -U postgres

- name: Install Drone.io
  with_items:
    - "present"
    - "restarted"
  docker:
    name: drone
    image: drone/drone:latest
    state: "{{ item }}"
    restart_policy: always
    detach: true
    privileged: true
    insecure_registry: yes
    env:
      DATABASE_DRIVER: postgres
      DATABASE_CONFIG: postgres://postgres::@172.17.42.1:5432/drone?sslmode=disable
      REMOTE_DRIVER: gogs
      REMOTE_CONFIG: http://172.17.42.1:3000
      DOCKER_HOST: unix://ver/run/docker.sock
      PLUGIN_FILTER: plugins/*
    volumes:
      - "/var/lib/drone:/var/lib/drone"
      - "/var/run/docker.sock:/var/run/docker.sock"
    expose:
      - "8000"
    ports:
      - "8000:8000"
  ignore_errors: yes
