---
# - name: Create Drone.id Directory
#   file: path=/var/lib/drone state=directory

# - name: Install Drone.io
#   with_items:
#     - "present"
#     - "restarted"
#   docker:
#     name: drone
#     image: mattgruter/drone:latest
#     state: "{{ item }}"
#     restart_policy: always
#     detach: true
#     privileged: true
#     insecure_registry: yes
#     env:
#       DATABASE_DRIVER: postgres
#       DATABASE_CONFIG: postgres://postgres::@172.17.42.1:5432/postgres?sslmode=disable
#       REMOTE_DRIVER: gogs
#       REMOTE_CONFIG: http://172.17.42.1:3000?open=true
#       DOCKER_HOST: unix://ver/run/docker.sock
#       PLUGIN_FILTER: plugins/*
#     volumes:
#       - "/var/lib/drone:/var/lib/drone"
#       - "/var/run/docker.sock:/var/run/docker.sock"
#     expose:
#       - "80"
#     ports:
#       - "8080:80"

- name: Install Drone.io
  yum: name=http://downloads.drone.io/master/drone.rpm state=present
  ignore_errors: yes

- name: Copy drone.toml
  copy: src=drone.toml dest=/etc/drone/drone.toml

- name: Start Drone.io
  service: name=drone state=restarted enabled=yes
