---
- name: Download libsqlite3
  get_url: url=https://www.sqlite.org/2015/sqlite-autoconf-3081101.tar.gz dest=/tmp/libsqlite3.tgz
  
- name: Extract libsqlite3
  unarchive: src=/tmp/libsqlite3.tgz dest=/tmp copy=no
  
- name: Build libsqlite3
  shell: cd /tmp/sqlite-autoconf-3081101 &&
         ./configure -prefix=/scratch/usr/local &&
         make &&
         make install
       
- name: Clone sassc
  git: repo="{{ item.repo }}" clone=yes dest="/tmp/{{ item.name }}"
  with_items:
    - { repo: 'https://github.com/sass/libsass.git', name: 'libsass' }
    - { repo: 'https://github.com/sass/sassc.git', name: 'sassc' }

- name: Build sassc
  environment:
    SASS_LIBSASS_PATH: /tmp/libsass
  shell: cd /tmp/sassc &&
         make &&
         install -t /usr/local/bin bin/sassc
    
- name: Create Drone.id Directory
  file: path=/var/lib/drone state=directory

- name: Create Gopath dir
  file: path=/tmp/gocode state=directory

- name: Clone Drone.io
  environment:
    GOPATH: /tmp/gocode
  git: repo=https://github.com/drone/drone.git clone=yes dest=/tmp/gocode/src/github.com/drone/drone

- name: Build Drone.io
  environment:
    GO15VENDOREXPERIMENT: 1
    GOPATH: /tmp/gocode
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tmp/gocode/bin
  shell: cd /tmp/gocode/src/github.com/drone/drone &&
         make deps &&
         make gen &&
         make build
#         go build --ldflags '-extldflags "-static"' -o drone_static

- name: Copy drone.toml
  copy: src=drone.toml dest=/etc/drone/drone.toml
